# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Install njsscan
      run: pip install --upgrade njsscan # Install njsscan
    - name: Run njsscan
      run: njsscan . # Run njsscan on the current directory
    - name: Save njsscan report
      run: njsscan . --json -o njsscan_report.json # Save the report in JSON format
    - name: Upload njsscan report
      uses: actions/upload-artifact@v3
      with:
        name: njsscan-report
        path: njsscan_report.json
    - name: Audit report
      run: npm audit --json | tee audit_report.json
    - name: Upload audit report
      uses: actions/upload-artifact@v3
      with:
        name: audit-report
        path: audit_report.json
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run build --if-present
